<script context="module">
  // Browsing state survives the page unmounting while a channel plays.
  let saved = { search: "", category: "", sourceFilter: "", visibleCount: 0, scrollTop: 0 };
</script>

<script>
  import { onMount, onDestroy, tick, createEventDispatcher } from "svelte";
  import { invoke } from "@tauri-apps/api/core";
  import { open as openFileDialog } from "@tauri-apps/plugin-dialog";

  const dispatch = createEventDispatcher();

  // Free FAST playlists generated by BuddyChewChew/app-m3u-generator.
  const PLAYLIST_BASE = "https://raw.githubusercontent.com/BuddyChewChew/app-m3u-generator/main/playlists/";
  const SERVICES = [
    { id: "plutotv", name: "Pluto TV", color: "#fde047", regions: "us ca gb de fr es it br ar cl dk mx no se all" },
    { id: "plex", name: "Plex", color: "#e5a00d", regions: "us ca gb au fr mx nz es all" },
    { id: "samsungtvplus", name: "Samsung TV Plus", color: "#60a5fa", regions: "us ca gb de fr es it at ch in kr all" },
    { id: "roku", name: "The Roku Channel", color: "#a78bfa", regions: "all" },
  ].map((s) => ({ ...s, regions: s.regions.split(" ") }));

  const REGION_NAMES = {
    us: "United States", ca: "Canada", gb: "United Kingdom", de: "Germany", fr: "France",
    es: "Spain", it: "Italy", br: "Brazil", ar: "Argentina", cl: "Chile", dk: "Denmark",
    mx: "Mexico", no: "Norway", se: "Sweden", au: "Australia", nz: "New Zealand",
    at: "Austria", ch: "Switzerland", in: "India", kr: "South Korea", all: "All regions",
  };
  const PAGE_SIZE = 120;
  const RECENT_LIMIT = 12;
  const FAVORITES = "__favorites";
  const RECENT = "__recent";

  let sources = [];
  let channels = [];
  let loaded = false;
  let busy = null; // source id or "add" while a playlist is downloading
  let error = null;

  let showSources = false;
  let search = saved.search;
  let category = saved.category;
  let sourceFilter = saved.sourceFilter;
  let visibleCount = PAGE_SIZE;
  let sentinel;
  let observer;

  let customName = "";
  let customUrl = "";
  let pickedRegion = Object.fromEntries(SERVICES.map((s) => [s.id, s.regions[0]]));

  let favorites = readList("liveTvFavorites");
  let recent = readList("liveTvRecent");
  let brokenLogos = new Set();

  function readList(key) {
    try {
      const value = JSON.parse(localStorage.getItem(key) || "[]");
      return Array.isArray(value) ? value : [];
    } catch {
      return [];
    }
  }

  function writeList(key, value) {
    try {
      localStorage.setItem(key, JSON.stringify(value));
    } catch {}
  }

  function apply(data) {
    sources = data.sources || [];
    channels = data.channels || [];
  }

  async function run(tag, action) {
    if (busy) return;
    busy = tag;
    error = null;
    try {
      apply(await action());
      return true;
    } catch (e) {
      error = String(e);
      return false;
    } finally {
      busy = null;
    }
  }

  const playlistUrl = (service, region) => `${PLAYLIST_BASE}${service.id}_${region}.m3u`;

  async function addService(service) {
    const region = pickedRegion[service.id];
    const name = region === "all" ? service.name : `${service.name} · ${region.toUpperCase()}`;
    await run("add", () => invoke("add_live_source", { name, location: playlistUrl(service, region) }));
  }

  async function addCustom() {
    if (!customUrl.trim()) return;
    if (await run("add", () => invoke("add_live_source", { name: customName, location: customUrl }))) {
      customName = "";
      customUrl = "";
    }
  }

  async function importFile() {
    const path = await openFileDialog({
      multiple: false,
      filters: [{ name: "M3U playlist", extensions: ["m3u", "m3u8"] }],
    }).catch(() => null);
    if (!path) return;
    const name = String(path).split(/[\\/]/).pop().replace(/\.m3u8?$/i, "");
    await run("add", () => invoke("add_live_source", { name, location: String(path) }));
  }

  const refreshSource = (source) => run(source.id, () => invoke("refresh_live_source", { id: source.id }));

  async function removeSource(source) {
    if (await run(source.id, () => invoke("remove_live_source", { id: source.id }))) {
      if (sourceFilter === source.id) sourceFilter = "";
    }
  }

  function toggleFavorite(channel) {
    favorites = favorites.includes(channel.url)
      ? favorites.filter((u) => u !== channel.url)
      : [channel.url, ...favorites];
    writeList("liveTvFavorites", favorites);
  }

  function play(channel, list) {
    saved = {
      search, category, sourceFilter, visibleCount,
      scrollTop: document.getElementById("main-content")?.scrollTop || 0,
    };
    recent = [channel.url, ...recent.filter((u) => u !== channel.url)].slice(0, RECENT_LIMIT);
    writeList("liveTvRecent", recent);
    const lineup = list.map((c) => ({ name: c.name, url: c.url, logo: c.logo }));
    window.dispatchEvent(new CustomEvent("openVideoPlayer", {
      detail: {
        src: channel.url,
        title: channel.name,
        channelLogo: channel.logo,
        live: true,
        channels: lineup,
        channelIndex: lineup.findIndex((c) => c.url === channel.url),
      },
    }));
  }

  function initials(name) {
    return name.replace(/[^\p{L}\p{N} ]/gu, "").split(/\s+/).filter(Boolean).slice(0, 2)
      .map((w) => w[0]).join("").toUpperCase() || "TV";
  }

  function updatedLabel(timestamp) {
    if (!timestamp) return "Not refreshed yet";
    const minutes = Math.round((Date.now() / 1000 - timestamp) / 60);
    if (minutes < 1) return "Updated just now";
    if (minutes < 60) return `Updated ${minutes} min ago`;
    const hours = Math.round(minutes / 60);
    if (hours < 48) return `Updated ${hours} h ago`;
    return `Updated ${Math.round(hours / 24)} days ago`;
  }

  $: addedLocations = new Set(sources.map((s) => s.location));
  $: sourceNames = Object.fromEntries(sources.map((s) => [s.id, s.name]));
  $: countBySource = channels.reduce((m, c) => ((m[c.source_id] = (m[c.source_id] || 0) + 1), m), {});
  $: scoped = sourceFilter ? channels.filter((c) => c.source_id === sourceFilter) : channels;
  $: groups = [...scoped.reduce((m, c) => m.set(c.group, (m.get(c.group) || 0) + 1), new Map())]
    .sort((a, b) => a[0].localeCompare(b[0]));
  $: favoriteChannels = favorites.map((u) => scoped.find((c) => c.url === u)).filter(Boolean);
  $: recentChannels = recent.map((u) => scoped.find((c) => c.url === u)).filter(Boolean);
  $: if (loaded && category && !(
      category === FAVORITES ? favoriteChannels.length
      : category === RECENT ? recentChannels.length
      : groups.some(([g]) => g === category))) category = "";
  $: query = search.trim().toLowerCase();
  $: filtered = (category === FAVORITES ? favoriteChannels
      : category === RECENT ? recentChannels
      : category ? scoped.filter((c) => c.group === category)
      : scoped)
    .filter((c) => !query || c.name.toLowerCase().includes(query) || c.group.toLowerCase().includes(query));
  $: query, category, sourceFilter, (visibleCount = PAGE_SIZE);
  $: shown = filtered.slice(0, visibleCount);
  $: showRecentRow = !category && !query && recentChannels.length > 0;
  $: if (sentinel && observer) { observer.disconnect(); observer.observe(sentinel); }

  onMount(async () => {
    observer = new IntersectionObserver((entries) => {
      if (entries.some((e) => e.isIntersecting) && visibleCount < filtered.length) {
        visibleCount += PAGE_SIZE;
      }
    }, { root: document.getElementById("main-content"), rootMargin: "600px" });
    try {
      apply(await invoke("get_live_channels"));
    } catch (e) {
      error = String(e);
    }
    loaded = true;
    if (sources.length === 0) showSources = true;
    if (saved.scrollTop) {
      visibleCount = Math.max(PAGE_SIZE, saved.visibleCount);
      await tick();
      const scroller = document.getElementById("main-content");
      if (scroller) scroller.scrollTop = saved.scrollTop;
      saved.scrollTop = 0;
    }
  });

  onDestroy(() => observer?.disconnect());
</script>

<div class="live-tv">
  <header class="live-header">
    <button class="icon-btn" on:click={() => dispatch("close")} aria-label="Back to home">
      <i class="ri-arrow-left-line"></i>
    </button>
    <div class="live-heading">
      <h1>Live TV</h1>
      {#if channels.length > 0}
        <span class="live-count">{channels.length.toLocaleString()} channels · {sources.length} {sources.length === 1 ? "source" : "sources"}</span>
      {/if}
    </div>
    <div class="header-spacer"></div>
    {#if channels.length > 0}
      <label class="search-field">
        <i class="ri-search-line"></i>
        <input type="text" placeholder="Search channels" bind:value={search} />
        {#if search}
          <button class="clear-search" on:click={() => (search = "")} aria-label="Clear search"><i class="ri-close-line"></i></button>
        {/if}
      </label>
    {/if}
    <button class="pill-btn" class:active={showSources} on:click={() => (showSources = !showSources)}>
      <i class="ri-play-list-add-line"></i> Sources
    </button>
  </header>

  {#if error}
    <div class="live-error" role="alert">
      <i class="ri-error-warning-line"></i>
      <span>{error}</span>
      <button class="icon-btn small" on:click={() => (error = null)} aria-label="Dismiss"><i class="ri-close-line"></i></button>
    </div>
  {/if}

  {#if showSources && loaded}
    <section class="sources-panel">
      {#if sources.length === 0}
        <div class="welcome">
          <h2>Free live channels, no account needed</h2>
          <p>Add a free lineup from one of these services, or bring your own M3U playlist. Channel availability varies by region and can change without notice.</p>
        </div>
      {/if}

      <div class="service-grid">
        {#each SERVICES as service}
          {@const location = playlistUrl(service, pickedRegion[service.id])}
          <div class="service-card" style="--service: {service.color}">
            <div class="service-name">{service.name}</div>
            <div class="service-row">
              {#if service.regions.length > 1}
                <select bind:value={pickedRegion[service.id]} aria-label="{service.name} region">
                  {#each service.regions as region}
                    <option value={region}>{REGION_NAMES[region] || region.toUpperCase()}</option>
                  {/each}
                </select>
              {:else}
                <span class="region-fixed">{REGION_NAMES[service.regions[0]]}</span>
              {/if}
              <button class="add-btn" disabled={!!busy || addedLocations.has(location)} on:click={() => addService(service)}>
                {#if addedLocations.has(location)}
                  <i class="ri-check-line"></i> Added
                {:else if busy === "add"}
                  <i class="ri-loader-4-line spin"></i>
                {:else}
                  <i class="ri-add-line"></i> Add
                {/if}
              </button>
            </div>
          </div>
        {/each}
      </div>

      <form class="custom-row" on:submit|preventDefault={addCustom}>
        <input class="text-input name" type="text" placeholder="Name (optional)" bind:value={customName} />
        <input class="text-input url" type="text" placeholder="M3U playlist URL" bind:value={customUrl} />
        <button class="add-btn" type="submit" disabled={!!busy || !customUrl.trim()}>
          <i class="ri-link"></i> Add URL
        </button>
        <button class="add-btn ghost" type="button" disabled={!!busy} on:click={importFile}>
          <i class="ri-folder-open-line"></i> Import file
        </button>
      </form>

      {#if sources.length > 0}
        <ul class="source-list">
          {#each sources as source (source.id)}
            <li class="source-item">
              <div class="source-info">
                <span class="source-name">{source.name}</span>
                <span class="source-meta">{(countBySource[source.id] || 0).toLocaleString()} channels · {updatedLabel(source.updated_at)}</span>
              </div>
              <button class="icon-btn small" disabled={!!busy} on:click={() => refreshSource(source)} aria-label="Refresh {source.name}" title="Refresh">
                <i class="ri-refresh-line" class:spin={busy === source.id}></i>
              </button>
              <button class="icon-btn small danger" disabled={!!busy} on:click={() => removeSource(source)} aria-label="Remove {source.name}" title="Remove">
                <i class="ri-delete-bin-line"></i>
              </button>
            </li>
          {/each}
        </ul>
      {/if}
      <p class="attribution">Featured lineups come from the community-maintained <em>app-m3u-generator</em> project and are not affiliated with the listed services.</p>
    </section>
  {/if}

  {#if channels.length > 0}
    <div class="filters">
      {#if sources.length > 1}
        <select class="source-select" bind:value={sourceFilter} aria-label="Source">
          <option value="">All sources</option>
          {#each sources as source}
            <option value={source.id}>{source.name}</option>
          {/each}
        </select>
      {/if}
      <div class="chips">
        <button class="chip" class:active={!category} on:click={() => (category = "")}>All</button>
        {#if favoriteChannels.length > 0}
          <button class="chip" class:active={category === FAVORITES} on:click={() => (category = FAVORITES)}>
            <i class="ri-star-fill"></i> Favorites
          </button>
        {/if}
        {#if recentChannels.length > 0}
          <button class="chip" class:active={category === RECENT} on:click={() => (category = RECENT)}>
            <i class="ri-history-line"></i> Recent
          </button>
        {/if}
        {#each groups as [group, count]}
          <button class="chip" class:active={category === group} on:click={() => (category = group)}>
            {group} <span class="chip-count">{count}</span>
          </button>
        {/each}
      </div>
    </div>

    {#if showRecentRow}
      <h2 class="row-title">Continue watching</h2>
      <div class="recent-row">
        {#each recentChannels as channel (channel.url)}
          <button class="recent-card" on:click={() => play(channel, recentChannels)} title={channel.name}>
            <div class="logo-box">
              {#if channel.logo && !brokenLogos.has(channel.logo)}
                <img src={channel.logo} alt="" loading="lazy" on:error={() => (brokenLogos = new Set(brokenLogos).add(channel.logo))} />
              {:else}
                <span class="logo-fallback">{initials(channel.name)}</span>
              {/if}
            </div>
            <span class="recent-name">{channel.name}</span>
          </button>
        {/each}
      </div>
      <h2 class="row-title">All channels</h2>
    {/if}

    {#if filtered.length === 0}
      <div class="empty">
        <i class="ri-tv-2-line"></i>
        <p>No channels match{query ? ` "${search.trim()}"` : ""}.</p>
      </div>
    {:else}
      <div class="channel-grid">
        {#each shown as channel (channel.source_id + channel.url)}
          <div class="channel-card">
            <button class="channel-main" on:click={() => play(channel, filtered)}>
              <div class="logo-box">
                {#if channel.logo && !brokenLogos.has(channel.logo)}
                  <img src={channel.logo} alt="" loading="lazy" on:error={() => (brokenLogos = new Set(brokenLogos).add(channel.logo))} />
                {:else}
                  <span class="logo-fallback">{initials(channel.name)}</span>
                {/if}
                <span class="play-overlay"><i class="ri-play-fill"></i></span>
              </div>
              <div class="channel-text">
                <span class="channel-name">{#if channel.number}<span class="channel-number">{channel.number}</span>{/if}{channel.name}</span>
                <span class="channel-meta">{channel.group}{#if sources.length > 1 && !sourceFilter} · {sourceNames[channel.source_id]}{/if}</span>
              </div>
            </button>
            <button
              class="fav-btn"
              class:on={favorites.includes(channel.url)}
              on:click={() => toggleFavorite(channel)}
              aria-label={favorites.includes(channel.url) ? `Remove ${channel.name} from favorites` : `Add ${channel.name} to favorites`}
              aria-pressed={favorites.includes(channel.url)}
            >
              <i class={favorites.includes(channel.url) ? "ri-star-fill" : "ri-star-line"}></i>
            </button>
          </div>
        {/each}
      </div>
      {#if visibleCount < filtered.length}
        <div class="sentinel" bind:this={sentinel}>
          <button class="pill-btn" on:click={() => (visibleCount += PAGE_SIZE)}>Show more</button>
        </div>
      {/if}
    {/if}
  {:else if loaded && !showSources}
    <div class="empty">
      <i class="ri-tv-2-line"></i>
      <p>No channels yet.</p>
      <button class="pill-btn" on:click={() => (showSources = true)}><i class="ri-add-line"></i> Add a source</button>
    </div>
  {/if}
</div>

<style>
  .live-tv {
    padding: var(--spacing-2xl) var(--spacing-3xl) 48px;
    color: var(--text-primary);
  }

  .live-header {
    display: flex;
    align-items: center;
    gap: var(--spacing-md);
    flex-wrap: wrap;
    margin-bottom: var(--spacing-xl);
  }

  .live-heading h1 {
    margin: 0;
    font-size: 28px;
    font-weight: 700;
    letter-spacing: -0.03em;
  }

  .live-count {
    font-size: 13px;
    color: var(--text-tertiary);
  }

  .header-spacer { flex: 1; }

  button { font-family: inherit; }

  .icon-btn {
    width: 36px;
    height: 36px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    border-radius: var(--border-radius-md);
    border: 1px solid rgba(255, 255, 255, 0.06);
    background: rgba(255, 255, 255, 0.04);
    color: var(--text-secondary);
    font-size: 18px;
    cursor: pointer;
    transition: all 0.2s ease;
  }
  .icon-btn:hover:not(:disabled) { background: rgba(255, 255, 255, 0.12); color: var(--text-primary); }
  .icon-btn:disabled { opacity: 0.4; cursor: default; }
  .icon-btn.small { width: 30px; height: 30px; font-size: 16px; border-radius: var(--border-radius-sm); }
  .icon-btn.danger:hover:not(:disabled) { background: rgba(239, 68, 68, 0.15); color: #f87171; }

  .pill-btn {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    height: 36px;
    padding: 0 16px;
    border-radius: var(--border-radius-pill);
    border: 1px solid rgba(255, 255, 255, 0.08);
    background: rgba(255, 255, 255, 0.05);
    color: var(--text-primary);
    font-size: 13px;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s ease;
  }
  .pill-btn:hover, .pill-btn.active {
    background: color-mix(in srgb, var(--accent-color) 22%, transparent);
    border-color: color-mix(in srgb, var(--accent-color) 45%, transparent);
  }

  .search-field {
    display: flex;
    align-items: center;
    gap: 8px;
    height: 36px;
    width: min(320px, 100%);
    padding: 0 12px;
    border-radius: var(--border-radius-pill);
    border: 1px solid rgba(255, 255, 255, 0.08);
    background: rgba(255, 255, 255, 0.04);
    color: var(--text-tertiary);
  }
  .search-field:focus-within { border-color: color-mix(in srgb, var(--accent-color) 55%, transparent); }
  .search-field input {
    flex: 1;
    min-width: 0;
    border: none;
    outline: none;
    background: transparent;
    color: var(--text-primary);
    font: inherit;
    font-size: 13px;
  }
  .clear-search {
    border: none;
    background: none;
    color: var(--text-tertiary);
    cursor: pointer;
    padding: 0;
    font-size: 16px;
    display: flex;
  }

  .live-error {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 12px 10px 16px;
    margin-bottom: var(--spacing-lg);
    border-radius: var(--border-radius-md);
    background: rgba(239, 68, 68, 0.1);
    border: 1px solid rgba(239, 68, 68, 0.3);
    color: #fca5a5;
    font-size: 13px;
  }
  .live-error span { flex: 1; }

  .sources-panel {
    padding: var(--spacing-xl);
    margin-bottom: var(--spacing-2xl);
    border-radius: var(--border-radius-lg);
    background: rgba(255, 255, 255, 0.025);
    border: 1px solid rgba(255, 255, 255, 0.06);
  }

  .welcome h2 { margin: 0 0 6px; font-size: 18px; font-weight: 600; }
  .welcome p { margin: 0 0 var(--spacing-lg); color: var(--text-secondary); font-size: 13px; max-width: 640px; line-height: 1.5; }

  .service-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
    gap: var(--spacing-md);
  }

  .service-card {
    padding: 14px;
    border-radius: var(--border-radius-md);
    background: linear-gradient(145deg, color-mix(in srgb, var(--service) 14%, transparent), rgba(255, 255, 255, 0.02));
    border: 1px solid color-mix(in srgb, var(--service) 22%, transparent);
  }
  .service-name { font-weight: 600; font-size: 14px; margin-bottom: 10px; }
  .service-row { display: flex; gap: 8px; align-items: center; }
  .region-fixed { flex: 1; font-size: 13px; color: var(--text-secondary); }

  select, .text-input {
    height: 32px;
    padding: 0 10px;
    border-radius: var(--border-radius-sm);
    border: 1px solid rgba(255, 255, 255, 0.1);
    background: rgba(0, 0, 0, 0.35);
    color: var(--text-primary);
    font: inherit;
    font-size: 13px;
    outline: none;
  }
  select:focus, .text-input:focus { border-color: color-mix(in srgb, var(--accent-color) 55%, transparent); }
  .service-row select { flex: 1; min-width: 0; }
  option { background: #151515; }

  .add-btn {
    height: 32px;
    padding: 0 12px;
    display: inline-flex;
    align-items: center;
    gap: 4px;
    border-radius: var(--border-radius-sm);
    border: 1px solid color-mix(in srgb, var(--accent-color) 45%, transparent);
    background: color-mix(in srgb, var(--accent-color) 22%, transparent);
    color: var(--text-primary);
    font-size: 13px;
    font-weight: 500;
    white-space: nowrap;
    cursor: pointer;
    transition: all 0.2s ease;
  }
  .add-btn:hover:not(:disabled) { background: color-mix(in srgb, var(--accent-color) 35%, transparent); }
  .add-btn:disabled { opacity: 0.5; cursor: default; }
  .add-btn.ghost { background: rgba(255, 255, 255, 0.04); border-color: rgba(255, 255, 255, 0.1); }

  .custom-row {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin-top: var(--spacing-lg);
  }
  .text-input.name { width: 180px; }
  .text-input.url { flex: 1; min-width: 220px; }

  .source-list {
    list-style: none;
    margin: var(--spacing-lg) 0 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .source-item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 8px 8px 14px;
    border-radius: var(--border-radius-sm);
    background: rgba(255, 255, 255, 0.03);
  }
  .source-info { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 2px; }
  .source-name { font-size: 13px; font-weight: 500; }
  .source-meta { font-size: 12px; color: var(--text-tertiary); }

  .attribution { margin: var(--spacing-lg) 0 0; font-size: 11px; color: var(--text-tertiary); }

  .filters {
    display: flex;
    align-items: center;
    gap: var(--spacing-md);
    margin-bottom: var(--spacing-xl);
    min-width: 0;
  }
  .source-select { flex-shrink: 0; height: 34px; border-radius: var(--border-radius-pill); }
  .chips {
    display: flex;
    gap: 8px;
    overflow-x: auto;
    padding-bottom: 4px;
    scrollbar-width: thin;
    min-width: 0;
  }
  .chip {
    flex-shrink: 0;
    display: inline-flex;
    align-items: center;
    gap: 6px;
    height: 32px;
    padding: 0 14px;
    border-radius: var(--border-radius-pill);
    border: 1px solid rgba(255, 255, 255, 0.07);
    background: rgba(255, 255, 255, 0.04);
    color: var(--text-secondary);
    font-size: 13px;
    cursor: pointer;
    transition: all 0.2s ease;
    white-space: nowrap;
  }
  .chip:hover { color: var(--text-primary); background: rgba(255, 255, 255, 0.08); }
  .chip.active {
    color: var(--text-primary);
    background: color-mix(in srgb, var(--accent-color) 24%, transparent);
    border-color: color-mix(in srgb, var(--accent-color) 50%, transparent);
  }
  .chip-count { font-size: 11px; color: var(--text-tertiary); font-variant-numeric: tabular-nums; }

  .row-title { font-size: 18px; font-weight: 600; letter-spacing: -0.02em; margin: 0 0 var(--spacing-md); }

  .recent-row {
    display: flex;
    gap: var(--spacing-md);
    overflow-x: auto;
    padding-bottom: 8px;
    margin-bottom: var(--spacing-2xl);
  }
  .recent-card {
    flex: 0 0 150px;
    display: flex;
    flex-direction: column;
    gap: 8px;
    padding: 0;
    border: none;
    background: none;
    color: var(--text-primary);
    cursor: pointer;
    text-align: left;
  }
  .recent-card .logo-box { aspect-ratio: 16 / 10; }
  .recent-name { font-size: 13px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

  .channel-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(190px, 1fr));
    gap: var(--spacing-lg);
  }

  .channel-card { position: relative; }

  .channel-main {
    width: 100%;
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 0;
    border: none;
    background: none;
    color: inherit;
    text-align: left;
    cursor: pointer;
  }

  .logo-box {
    position: relative;
    width: 100%;
    aspect-ratio: 16 / 10;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 18px;
    box-sizing: border-box;
    border-radius: var(--border-radius-md);
    background: radial-gradient(circle at 30% 20%, rgba(255, 255, 255, 0.08), rgba(255, 255, 255, 0.02) 70%);
    border: 1px solid rgba(255, 255, 255, 0.06);
    box-shadow: var(--shadow-highlight), var(--shadow-depth);
    overflow: hidden;
    transition: transform 0.25s cubic-bezier(0.4, 0, 0.2, 1), border-color 0.25s ease;
  }
  .logo-box img { max-width: 100%; max-height: 100%; object-fit: contain; }
  .logo-fallback {
    font-size: 26px;
    font-weight: 700;
    letter-spacing: 0.02em;
    color: var(--text-tertiary);
  }

  .play-overlay {
    position: absolute;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    background: rgba(0, 0, 0, 0.55);
    font-size: 34px;
    opacity: 0;
    transition: opacity 0.2s ease;
  }

  .channel-main:hover .logo-box,
  .channel-main:focus-visible .logo-box,
  .recent-card:hover .logo-box {
    transform: translateY(-3px);
    border-color: color-mix(in srgb, var(--accent-color) 55%, transparent);
  }
  .channel-main:hover .play-overlay,
  .channel-main:focus-visible .play-overlay { opacity: 1; }

  .channel-text { display: flex; flex-direction: column; gap: 2px; min-width: 0; padding-right: 30px; }
  .channel-name {
    font-size: 14px;
    font-weight: 500;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .channel-number {
    margin-right: 6px;
    color: var(--text-tertiary);
    font-variant-numeric: tabular-nums;
  }
  .channel-meta {
    font-size: 12px;
    color: var(--text-tertiary);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .fav-btn {
    position: absolute;
    right: 0;
    bottom: 4px;
    width: 28px;
    height: 28px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: none;
    border-radius: 50%;
    background: none;
    color: var(--text-tertiary);
    font-size: 16px;
    cursor: pointer;
    transition: color 0.2s ease, background 0.2s ease;
  }
  .fav-btn:hover { background: rgba(255, 255, 255, 0.08); color: var(--text-primary); }
  .fav-btn.on { color: #facc15; }

  .sentinel { display: flex; justify-content: center; padding: var(--spacing-2xl) 0; }

  .empty {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 10px;
    padding: 72px 0;
    color: var(--text-tertiary);
  }
  .empty i { font-size: 44px; }
  .empty p { margin: 0; font-size: 14px; }

  .spin { display: inline-block; animation: spin 0.9s linear infinite; }
  @keyframes spin { to { transform: rotate(360deg); } }

  @media (max-width: 640px) {
    .live-tv { padding: var(--spacing-lg) var(--spacing-lg) 40px; }
    .channel-grid { grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: var(--spacing-md); }
    .search-field { order: 5; width: 100%; }
  }

  @media (prefers-reduced-motion: reduce) {
    .logo-box, .spin { transition: none; animation: none; }
  }
</style>
